# Generated by Django 5.1.3 on 2025-05-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_responsavel_grau_de_parentesco"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crianca",
            name="necessidade_especial",
        ),
        migrations.DeleteModel(
            name="Necessidade_especial",
        ),
    ]
