# Generated by Django 5.1.3 on 2025-05-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_remove_relatorioanual_arquivo_pdf_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instituicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_da_instituicao", models.CharField(max_length=50)),
                ("cnpj", models.IntegerField(blank=True, null=True)),
                ("tempo_de_fundacao", models.CharField(blank=True, max_length=20)),
                ("publico_alvo", models.CharField(blank=True, max_length=100)),
                ("capacidade", models.CharField(blank=True, max_length=200)),
                ("link_abrigo", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name_plural": "Cadastro de Abrigos",
            },
        ),
        migrations.RemoveField(
            model_name="crianca",
            name="filial",
        ),
        migrations.RemoveField(
            model_name="crianca",
            name="responsavel",
        ),
        migrations.RemoveField(
            model_name="participacao",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="participacao",
            name="atividade",
        ),
        migrations.DeleteModel(
            name="Responsavel",
        ),
        migrations.DeleteModel(
            name="Crianca",
        ),
        migrations.DeleteModel(
            name="Participacao",
        ),
    ]
