# Generated by Django 5.1.3 on 2025-05-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_instituicao_remove_crianca_filial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodePix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='doacao/')),
            ],
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='capacidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='tempo_de_fundacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo de fundação (em anos)'),
        ),
    ]
