# Generated by Django 5.1.3 on 2025-05-24 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_qrcodepix_alter_instituicao_capacidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcodepix',
            options={'verbose_name': 'QR Code Pix', 'verbose_name_plural': 'QR Code Pix'},
        ),
    ]
