# Generated by Django 5.1.3 on 2025-05-13 14:33

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_voluntario_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voluntario",
            name="idade",
            field=models.IntegerField(
                blank=True, null=True, validators=[events.models.validar_idade_minima]
            ),
        ),
    ]
