# Generated by Django 5.1.3 on 2025-05-24 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_qrcodepix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRCodePix',
        ),
    ]
