# Generated by Django 5.1.3 on 2025-05-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_voluntario"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="Pix",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
