# Generated by Django 5.1.3 on 2025-05-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_evento_pix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voluntario",
            name="comentario",
        ),
        migrations.AddField(
            model_name="voluntario",
            name="idade",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="voluntario",
            name="telefone",
            field=models.CharField(default="000000000", max_length=20),
        ),
        migrations.AlterField(
            model_name="voluntario",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
