# Generated by Django 5.1.3 on 2025-05-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_remove_voluntario_comentario_voluntario_idade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voluntario",
            name="telefone",
            field=models.CharField(default="", max_length=20),
        ),
    ]
