# Generated by Django 5.1.3 on 2025-05-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_voluntario_idade'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodePix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='doacao/')),
            ],
        ),
    ]
