# Generated by Django 5.1.3 on 2025-06-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Cadastro das atividades",
            },
        ),
        migrations.CreateModel(
            name="Filial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_filial",
                    models.CharField(
                        blank=True,
                        choices=[("", ""), ("", "")],
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instituicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_da_instituicao", models.CharField(max_length=50)),
                (
                    "tempo_de_fundacao",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Tempo de fundação (em anos)",
                    ),
                ),
                ("cnpj", models.CharField(max_length=14)),
                ("publico_alvo", models.CharField(blank=True, max_length=100)),
                ("capacidade", models.IntegerField(blank=True, null=True)),
                ("link_abrigo", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name_plural": "Cadastro de Abrigos",
            },
        ),
        migrations.CreateModel(
            name="QRCodePix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("imagem", models.ImageField(upload_to="doacao/")),
            ],
            options={
                "verbose_name": "Doação Pix QR Code",
                "verbose_name_plural": "Doação Pix QR Code",
            },
        ),
        migrations.CreateModel(
            name="RelatorioAnual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("imagem", models.ImageField(upload_to="relatorios_imagens/")),
                (
                    "link_relatorio",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("ano", models.IntegerField()),
            ],
        ),
    ]
