# Generated by Django 5.1.3 on 2025-06-11 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = []
