# Generated by Django 5.1.3 on 2025-06-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250611_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodePixFelicidade',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to='doacaoFelicidade/')),
            ],
            options={
                'verbose_name': 'Doação Pix QR Code (Felicidade Compartilhada)',
                'verbose_name_plural': 'Doação Pix QR Code (Felicidade Compartilhada)',
            },
        ),
        migrations.CreateModel(
            name='QRCodePixParceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='doacaoParceiros/')),
            ],
            options={
                'verbose_name': 'Doação Pix QR Code (Parceiros)',
                'verbose_name_plural': 'Doação Pix QR Code (Parceiros)',
            },
        ),
        migrations.DeleteModel(
            name='QRCodePix',
        ),
    ]
